USE kaloreaper;

ALTER DATABASE kaloreaper
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_polish_ci;

INSERT INTO product_category VALUES (1, 'Pieczywo');
INSERT INTO product_category VALUES (2, 'Nabiał');
INSERT INTO product_category VALUES (3, 'Mięso');
INSERT INTO product_category VALUES (4, 'Ryby');
INSERT INTO product_category VALUES (5, 'Owoce');
INSERT INTO product_category VALUES (6, 'Warzywa');
INSERT INTO product_category VALUES (7, 'Fast food');
INSERT INTO product_category VALUES (8, 'Słodycze');
INSERT INTO product_category VALUES (9, 'Napoje');
INSERT INTO product_category VALUES (10, 'Dania gotowe');
INSERT INTO product_category VALUES (11, 'Inne');



INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Actimel, mleko jogurtowe", 88, 2.7, 1.5, 16.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Advokat, likier", 280, 4.4, 6.0, 26.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Agrest", 60, 1.2, 0.9, 11.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ananas", 33, 0.2, 0.0, 7.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ananas, plastry w syropie", 84, 0.4, 0.1, 21.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ananas, dżem niskosłodzony", 157, 0.2, 0.1, 38.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Arbuz", 15, 0.3, 0.1, 3.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Awokado", 160, 2.0, 15.3, 7.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Babka biszkoptowa", 340, 8.2, 4.3, 67.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Bagietki francuskie", 282, 7.9, 1.7, 60.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Bakłażan", 21, 1.1, 0.1, 6.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Baleron gotowany", 244, 15.1, 20.2, 0.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Banan", 95, 1.0, 0.3, 23.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Baranina, łopatka", 284, 15.6, 25.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Baranina, udziec", 232, 18.0, 18.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Barszcz czerwony zabielany", 32, 2.0, 1.4, 3.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Barszcz ukraiński", 54, 2.1, 2.7, 6.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Barszcz z boćwiną", 29, 1.5, 1.7, 2.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Baton Bounty", 448, 4.2, 25.2, 56.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Baton Knoppers", 528, 8.0, 32.0, 52.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Baton Mars", 451, 3.6, 18.2, 68.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Baton Milky Way", 448, 3.6, 16.2, 71.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Baton Nestle Lion", 491, 7.4, 28.9, 52.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Baton Snickers", 497, 9.7, 28.2, 52.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Baton Twix", 487, 5.3, 23.2, 64.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Baton z indyka, szynkowy", 143, 14.9, 9.3, 0.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Baton z kurczaka", 144, 16.7, 8.6, 0.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Bażant, tuszka", 108, 22.3, 1.9, 0.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Benecol, margaryna", 540, 0.0, 60.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Befsztyk bity wiejskio", 258, 19.4, 19.6, 1.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Białko jaja kurzego", 49, 10.9, 0.2, 0.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Bigos", 119, 5.1, 9.9, 3.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Bitki wieprzowe", 195, 10.4, 16.1, 2.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Bitki wieprzowe w jarzynach", 198, 10.7, 16.0, 4.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Bitki wołowe", 102, 13.6, 4.3, 2.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Bitki wołowe w jarzynach", 116, 14.3, 4.4, 6.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Biszkopty, ciastka", 400, 9.3, 7.5, 73.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Bobo Fruit jabłkowy", 42, 0.1, 0.0, 10.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Boczek wieprzowy", 517, 10.1, 53.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Boćwina", 35, 2.1, 0.5, 5.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Boeuf Strogonow", 220, 19.5, 14.3, 3.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Borowik suszony", 342, 29.0, 10.0, 34.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Borowik świeży", 36, 5.4, 0.4, 2.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Bób", 66, 7.1, 0.4, 14.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Brando, landrynki", 390, 0.0, 0.0, 96.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Brandy, alkohol", 225, 0.0, 0.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Brokuły", 27, 3.0, 0.4, 5.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Brokuły mrożone", 24, 2.7, 0.4, 4.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Brukselka", 37, 4.7, 0.5, 8.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Brukselka mrożona", 36, 4.5, 0.5, 8.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Brukselka z wody", 110, 4.2, 7.1, 12.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Bryzol wołowy z polędwicy", 252, 24.6, 16.6, 1.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Brzoskwinia", 46, 1.0, 0.2, 11.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Brzoskwinia w syropie", 73, 0.4, 0.1, 18.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Brzoskwinie, dżem niskosłodzony", 155, 0.5, 0.1, 38.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Buchty drożdżowe", 303, 6.2, 11.0, 45.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Budyń czekoladowy", 95, 2.8, 2.1, 16.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Budyń waniliowy", 91, 2.5, 2.0, 15.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Bułka grahamka", 258, 8.2, 1.7, 56.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Bułka kajzerka", 226, 7.5, 3.6, 59.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Bułka maślana", 326, 7.7, 5.9, 61.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Bułka tarta", 363, 10.4, 2.1, 75.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Bułka pszenna, zwykła", 272, 7.3, 1.5, 58.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Bułka wrocławska", 293, 2.7, 0.4, 4.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Burak", 38, 1.8, 0.1, 9.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Buraki mrożone", 34, 1.6, 0.1, 8.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Buraki zasmażane", 83, 1.8, 5.5, 8.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Cappucino, proszek", 385, 5.3, 9.9, 68.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Cebula", 37, 1.4, 0.4, 6.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Cielęcina, łopatka", 105, 19.9, 2.8, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Cielęcina, z kością", 151, 19.7, 8.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Cielęcina, udziec", 108, 19.9, 3.1, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Chałka", 252, 5.8, 4.4, 47.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Chałwa", 531, 8.0, 31.0, 55.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Cheesburger", 278, 12.6, 11.8, 30.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Chipsy bekonowe", 537, 5.9, 38.0, 52.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Chipsy paprykowe", 549, 6.0, 40.0, 50.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Chipsy solone", 552, 5.6, 40.7, 49.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Cielęcina, bez kości", 108, 19.9, 3.1, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Cherry, brandy - alkohol", 265, 0.0, 0.0, 32.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Chleb baltonowski", 246, 5.9, 1.5, 55.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Chleb chrupki", 353, 8.7, 2.4, 78.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Chleb graham", 226, 7.6, 1.7, 49.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Chleb mazowiecki", 248, 6.3, 1.4, 56.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Chleb mieszany słonecznikowy", 246, 6.4, 4.5, 49.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Chleb praski", 244, 5.7, 1.3, 56.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Chleb pszenny", 249, 6.8, 1.4, 56.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Chleb staropolski", 219, 5.0, 1.7, 50.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Chleb wiejski", 239, 5.8, 1.3, 55.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Chleb zwykły", 245, 5.4, 1.3, 57.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Chleb praski", 244, 5.7, 1.3, 56.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Chleb żytni jasny", 241, 4.0, 1.3, 57.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Chleb żytni jasny mleczny", 253, 4.8, 1.8, 58.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Chleb żytni pełnoziarnisty", 237, 6.7, 1.8, 53.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Chleb żytni razowy", 223, 5.6, 1.7, 51.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Chleb żytni razowy na miodzie", 234, 5.3, 1.6, 54.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Chleb żytni razowy z soją i słonecznikiem", 244, 7.9, 3.7, 54.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Chleb żytni wileński", 225, 4.4, 1.5, 52.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Chrupki kukurydziane", 352, 8.9, 3.0, 78.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Chrzan", 67, 4.5, 0.6, 18.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ciastka francuskie", 432, 5.0, 26.8, 44.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ciastka karpatki", 449, 4.7, 30.9, 39.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ciastka napoleonki", 348, 5.9, 17.0, 43.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ciastka tortowe z owocami", 276, 3.2, 9.0, 47.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ciasto drożdżowe", 290, 7.4, 8.2, 47.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ciasto kruche podstawowe", 429, 5.2, 23.8, 49.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ciasto naleśnikowe bez piany", 174, 5.9, 4.3, 28.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ciasto naleśnikowe biszkoptowe", 187, 8.3, 6.0, 25.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Cielęcina w potrawce", 103, 13.5, 4.0, 4.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Cielęcina, łopatka", 106, 19.9, 2.8, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Cielęcina, sznyclówka", 105, 20.5, 2.4, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Cielęcina, udziec", 108, 19.9, 3.1, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Coca-cola", 42, 0.0, 0.0, 10.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Cukier", 405, 0.0, 0.0, 99.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Cukierki irysy", 421, 4.3, 10.7, 76.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Cukierki krówki", 412, 4.1, 10.6, 76.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Cukierki owocowe", 374, 0.3, 0.5, 92.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Cukinia", 15, 1.2, 0.1, 3.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Cukierki owocowe", 374, 0.3, 0.5, 92.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Curacao, likier - alkohol", 319, 0.0, 0.0, 27.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Cykoria", 21, 1.7, 0.2, 4.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Cytryna", 36, 0.8, 0.3, 9.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Czarne jagody", 45, 0.8, 0.6, 12.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Czekolada biała", 530, 7.7, 38.4, 51.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Czekolada deserowa", 531, 5.3, 28.9, 64.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Czekolada gorzka", 554, 6.7, 34.3, 56.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Czekolada kawowa", 526, 5.5, 29.0, 62.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Czekolada mleczna", 549, 9.8, 32.5, 54.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Czekolada mleczna z orzechami", 539, 8.6, 30.9, 57.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Czekolada nadziewana", 450, 3.9, 17.6, 68.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Czekoladki Ferrero Rocher", 562, 9.0, 40.2, 41.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Czekoladki Golden Nut", 576, 6.0, 39.0, 50.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Czekoladki Mon Cheri", 421, 3.2, 19.7, 57.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Czekoladki Raffaello", 600, 9.7, 46.6, 35.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Czekoladki Toffifee", 535, 6.0, 31.0, 58.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Czereśnie", 55, 1.0, 0.5, 11.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Czosnek", 144, 6.2, 0.5, 28.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ćwikła", 41, 1.6, 0.1, 10.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Daktyle suszone", 277, 2.0, 0.4, 74.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Danonki, jogurt do picia", 87, 2.8, 1.6, 15.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Delicje, ciastka", 376, 3.5, 8.4, 71.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Delma, margaryna", 496, 0.0, 55.0, 0.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Deser ryżowy jabłkowy", 134, 2.8, 3.0, 23.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Deser ryżowy waniliowy", 133, 3.0, 2.9, 23.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Deser czekoladow, Monte", 195, 2.8, 13.3, 15.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Deser twarogowy kakaowy", 156, 13.9, 6.2, 11.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Deser twarogowy truskawkowy", 170, 11.0, 5.8, 18.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Dorsz świeży", 78, 17.7, 0.7, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Dorsz świeży, filet", 78, 17.7, 0.7, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Dorsz w jarzynach", 117, 15.6, 4.9, 3.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Dorsz wędzony", 94, 22.1, 0.5, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Dorsz z rusztu", 172, 22.1, 9.1, 0.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Dorsz, filety po grecku", 152, 10.6, 10.8, 4.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Dorsz, filety smażone panierowane", 273, 19.1, 0.7, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Dorsz, kotlet mielony", 260, 14.9, 17.8, 10.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Dorsz, pulpety", 112, 14.2, 2.6, 8.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Dorsz, sałatka", 187, 9.8, 13.9, 7.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Drażetki Tic Tac", 390, 0.0, 0.0, 97.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Drożdze piekarskie", 132, 11.3, 2.0, 14.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Drożdżówka", 321, 6.0, 9.0, 50.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Dynia", 28, 1.3, 0.3, 7.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Dynia z pomidorami", 44, 1.2, 2.4, 6.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Dynia, pestki", 556, 24.5, 45.8, 18.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Dżem niskosłodzony", 163, 0.5, 0.0, 63.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Dżem wysokosłodzony", 257, 0.5, 0.2, 63.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Eklerki, ciastka", 301, 5.0, 9.0, 50.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Eklerki z bitą śmietaną", 317, 5.8, 18.0, 33.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Endywia", 17, 1.8, 0.6, 1.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Familijne, wafle", 533, 7.1, 29.6, 59.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Fasola biała, suche nasiona", 288, 21.4, 1.6, 61.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Fasola cięta, konserwowa", 16, 1.5, 0.2, 4.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Fasola szparagowa", 27, 2.4, 0.2, 7.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Fasolka flageolet konserwowa", 61, 6.3, 0.2, 15.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Fasolka po bretońsku", 141, 8.0, 6.6, 15.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Fasolka szparagowa", 97, 2.9, 6.9, 10.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Fasolka szparagowa, mrożona", 24, 2.2, 0.2, 6.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ferrero Rocher, czekoladki", 562, 9.0, 40.2, 41.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Figi suszone", 290, 3.6, 1.2, 78.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Flaki wołowe suche", 84, 16.0, 2.2, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Flaki wołowe na rosole", 71, 4.6, 4.2, 3.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Flądra świeża", 83, 16.5, 1.8, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Flora, margaryna", 328, 0.1, 35.0, 3.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Frytki mrożone", 172, 2.5, 5.5, 28.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Frytki z frytkownicy", 252, 3.0, 12.0, 33.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Frytki z piekarnika", 231, 3.5, 5.0, 37.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Galaretka z nóżek wieprzowych", 202, 16.9, 14.9, 0.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Gęś, tuszka", 339, 14.1, 31.8, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Gin, alkohol", 225, 0.0, 0.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Golden Nut, czekoladki", 576, 6.0, 39.0, 50.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Golonka wieprzowa ze skórą", 297, 18.6, 24.7, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Gołąbki tradycyjne", 108, 3.6, 6.7, 10.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Granat", 65, 2.4, 0.4, 13.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Grejpfrut", 36, 0.6, 0.2, 9.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Groch, suche nasiona", 293, 23.8, 1.4, 60.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Groszek zielony", 75, 6.7, 0.4, 17.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Groszek zielony, konserwowy", 63, 4.9, 0.2, 15.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Groszek zielony mrożony", 72, 6.4, 0.4, 16.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Groszek zielony z masłem", 100, 3.7, 6.8, 9.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Gruszka", 54, 0.6, 0.2, 14.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Gruszka suszona", 329, 0.7, 0.5, 80.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Gruszki w sosie waniliowym", 151, 1.6, 1.1, 34.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Gulasz wołowy", 148, 14.0, 9.2, 2.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Grześki, wafle", 550, 8.5, 34.5, 51.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Halibut biały, świeży", 98, 20.1, 1.9, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Hamburger", 268, 11.4, 9.5, 34.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Hamburger BicMac McDonald", 273, 11.4, 15.1, 22.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Hamburger McChicken McDonald", 295, 9.7, 15.9, 28.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Herbata bez cukru", 0, 0.1, 0.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Herbatniki", 437, 8.2, 11.0, 76.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Herbatniki Corso", 440, 5.0, 17.2, 67.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Herbatniki kakaowe", 474, 6.9, 22.3, 62.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Herbatniki kokosowe", 473, 6.4, 25.2, 59.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Herbatniki sezamowe", 503, 8.1, 28.6, 55.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Herbatniki w czekoladzie", 489, 6.3, 24.0, 63.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Herbatniki z cukrem", 460, 6.7, 17.2, 70.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Herbatniki z nadzieniem owocowym", 389, 3.8, 16.1, 58.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Homar", 85, 18.8, 0.9, 0.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Indyk, mięso z piersi bez skóry", 84, 19.2, 0.7, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Indyk, mięso z podudzia ze skórą", 142, 15.7, 8.9, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Indyk, udko ze skórą", 131, 18.4, 6.4, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Indyk, skrzydełko", 168, 16.5, 11.4, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Irysy, cukierki", 418, 4.3, 10.7, 76.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kabanosy", 326, 27.4, 24.3, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kabanosy z kurczaka", 247, 22.8, 17.4, 0.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kaczka, tuszka", 308, 13.5, 28.6, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kakako w proszku 16%", 448, 18.2, 21.7, 50.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kalafior", 22, 2.4, 0.2, 0.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kalafior mrożony", 20, 2.2, 0.2, 4.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kalafior z wody", 33, 2.0, 6.8, 5.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kalarepa", 29, 2.2, 0.3, 6.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kapusta biała", 29, 1.7, 0.2, 7.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kapusta biała zasmażana", 69, 1.6, 4.7, 7.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kapusta czerwona", 27, 1.9, 0.2, 6.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kapusta kwaszona", 12, 1.1, 0.2, 3.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kapusta pekińska", 12, 1.2, 0.2, 3.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kapusta włoska", 38, 3.3, 0.4, 7.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kapuśniak z kapusty kwaszonej", 21, 1.4, 1.2, 1.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kapuśniak z kapusty słodkiej", 31, 0.7, 2.1, 3.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Karmelki nadziewane", 378, 0.3, 0.5, 92.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Karmelki twarde", 399, 0.0, 0.0, 98.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Karp świeży", 110, 18.0, 4.2, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Jabłko", 46, 0.4, 0.4, 12.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Jabłko pieczone", 93, 0.3, 1.6, 20.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Jabłko suszone", 238, 2.1, 2.1, 62.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Jabłko w kruchym cieście", 348, 4.1, 17.4, 45.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Jagnięcina", 126, 20.4, 4.9, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Jagody", 62, 1.1, 0.9, 12.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Jagodowy dżem, niskosłodzony", 153, 0.3, 0.2, 38.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Jagodzianki", 314, 7.1, 5.4, 60.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Jajko kurze, białko", 46, 10.8, 0.0, 0.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Jajko kurze, całe", 150, 12.5, 10.7, 1.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Jajko kurze, żółtko", 355, 16.3, 31.9, 0.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Jajko sadzone", 181, 10.1, 15.2, 0.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Jajko smażone, jajecznica", 131, 10.0, 9.7, 0.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Jałowcówka, wódka", 226, 0.0, 0.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Jarmuż", 29, 3.3, 0.7, 6.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Jarzyny mrożone", 30, 2.8, 0.3, 7.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Jeżyki, ciastka", 457, 5.0, 21.3, 61.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Jeżyny", 71, 1.2, 0.4, 15.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Jogurt bananowy 1,5%", 70, 3.7, 1.5, 10.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Jogurt jagodowy 1,5%", 62, 3.7, 1.5, 8.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Jogurt morelowy 1,5%", 63, 4.2, 0.0, 6.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Jogurt naturalny 0,0%", 42, 3.7, 1.5, 8.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Jogurt naturalny 2,0%", 60, 4.3, 2.0, 6.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Jogurt owocowy 2,7%", 99, 3.3, 2.7, 13.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Jogurt truskawkowy 1,5%", 60, 3.7, 1.5, 8.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Jogurt wiśniowy 1,5%", 61, 3.7, 1.5, 8.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Karp w galarecie z warz.", 137, 26.1, 2.9, 2.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Karp z wody", 102, 16.0, 3.7, 2.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kasza gryczana", 336, 12.6, 3.1, 69.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kasza gryczana na sypko", 132, 4.5, 2.3, 25.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kasza jaglana", 346, 10.5, 2.9, 71.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kasza jęczm. na mleku", 63, 2.6, 2.2, 8.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kasza jęczm. perłowa", 327, 6.9, 2.2, 75.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kasza jęczm. pęczak", 334, 8.4, 2.0, 74.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kasza manna", 348, 8.7, 1.3, 76.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kasza manna na mleku", 67, 2.7, 2.1, 9.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kasza mana na wywarze jarzynowym", 21, 0.5, 0.8, 3.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kasza perłowa na sypko", 115, 2.2, 2.0, 23.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kaszanka z kurczaka", 204, 9.8, 11.7, 16.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kawa bez cukru", 2, 0.2, 0.0, 0.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kefir 2%", 51, 3.4, 2.0, 4.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Keks bakaliowy", 384, 6.4, 17.6, 53.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ketchup", 93, 27.4, 24.3, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kiełbasa jałowcowa", 236, 19.0, 17.9, 0.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kiełbasa krakowska sucha", 323, 25.6, 24.8, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kiełbasa mazurska", 129, 14.8, 7.7, 0.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kiełbasa mortadela", 205, 12.0, 17.7, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kiełbasa myśliwska sucha", 291, 27.8, 20.1, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kiełbasa parówka", 323, 11.0, 31.5, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kiełbasa podlaska", 232, 20.7, 16.7, 0.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kiełbasa podsuszana", 247, 17.3, 19.6, 0.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kiełbasa podwawelska", 247, 17.3, 19.6, 0.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kiełbasa szynk. z indyka", 88, 17.2, 2.0, 0.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kiełbasa szynk. z kurcz.", 110, 16.2, 5.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kiełbasa śląska", 210, 18.4, 15.3, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kiełbasa toruńska", 263, 20.9, 20.1, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kiełbasa zwyczajna", 209, 17.6, 15.6, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kiełbasa żywiecka", 315, 20.3, 26.3, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kisiel porzeczkowyy", 88, 0.3, 0.1, 23.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kisiel waniliowy", 121, 3.3, 4.5, 16.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kiszka jęczmienna", 194, 8.5, 12.6, 13.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kiszka krwista", 404, 14.2, 35.0, 9.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kiszka pasztetowa", 384, 12.5, 35.7, 4.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kiwi", 56, 0.9, 0.5, 13.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kiwi, dżem niskosł.", 154, 0.4, 0.2, 37.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Klopsiki cielęce mielone", 250, 16.2, 14.6, 14.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Klopsiki mielone", 272, 13.5, 17.5, 15.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kluski kładzione", 165, 5.1, 1.3, 33.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kluski lane", 93, 4.1, 2.0, 14.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kluski lane na mleku", 70, 3.6, 3.1, 6.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kluski śląskie", 169, 2.6, 3.8, 32.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Knedle ze śliwkami", 161, 2.7, 5.9, 25.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kompot z jabłek", 51, 0.2, 0.1, 13.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kompot z wiśni", 69, 0.2, 0.1, 16.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Koncentrat pomid. 30%", 92, 5.6, 1.5, 16.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Koper", 26, 2.8, 0.4, 6.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kopytka", 143, 4.0, 0.7, 31.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kotlet cielęcy panier.", 365, 27.1, 21.3, 17.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kotlet drobiowy panier.", 248, 19.7, 15.7, 7.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kotlet drobiowy soute", 241, 20.3, 16.5, 3.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kotlet drob. mielony", 382, 19.9, 27.8, 14.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kotlet mielony", 284, 13.0, 21.1, 11.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kotlet schabowy", 351, 19.0, 24.1, 15.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kotlety z jaj", 275, 7.9, 22.7, 10.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kotlety ziemniaczane", 241, 4.3, 12.8, 29.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Krem z ziel. groszku", 63, 3.1, 3.8, 5.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Królik, tuszka", 156, 21.0, 8.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Krupnik z kaszy grycz.", 43, 1.7, 1.2, 7.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Krupnik z kaszy jęcz.", 40, 1.5, 0.9, 7.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Krupnik z ryżu", 43, 1.5, 1.1, 7.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kukurydza", 110, 3.7, 1.5, 23.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kukurydza konserwowa", 102, 2.9, 1.2, 23.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kura w galarecie", 192, 27.3, 8.9, 1.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kura, tuszka", 202, 18.5, 14.3, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kurczak fasz. pieczony", 199, 20.5, 11.9, 2.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kurczak gotowany w jarz.", 99, 7.6, 6.4, 4.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kurczak pieczony", 179, 16.4, 12.7, 0.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kurczak, piersi", 99, 21.5, 1.3, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kurczak, udko", 158, 16.8, 10.2, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kurczak, skrzydełko", 186, 19.2, 12.2, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kurczak, tuszka", 158, 18.6, 9.3, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kurczak, wątróbka", 136, 19.1, 6.3, 0.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kurczak, żoładek", 114, 18.2, 4.2, 0.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kurka świeża, grzyb", 23, 1.0, 0.4, 3.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Kuropatwa, tuszka", 112, 24.3, 1.4, 0.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Landrynki Brando", 390, 0.0, 0.0, 96.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Likier Advocat", 280, 4.4, 6.0, 28.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Likier Curacao", 319, 0.0, 0.0, 27.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Lody bajaliowe", 133, 2.2, 7.2, 14.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Lody czekoladowe", 128, 2.1, 6.1, 16.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Lody orzechowe", 135, 2.4, 8.0, 13.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Lody owocowe", 114, 1.5, 5.3, 15.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Lody śmietankowe", 135, 1.7, 7.6, 15.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Lody waniliowe", 120, 1.8, 6.5, 13.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Łopatka barania", 287, 15.5, 25.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Łopatka cielęca", 105, 19.5, 25.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Łopatka wieprzowa", 259, 16.0, 21.7, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Łosoś smażony saute", 379, 21.1, 31.4, 4.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Łosoś świeży", 201, 19.9, 13.6, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Łosoś wędzony", 162, 21.5, 8.4, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Łosoś z rusztu", 283, 20.7, 22.3, 0.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Maggi, przyprawa", 17, 2.7, 0.0, 1.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Majonez", 714, 1.3, 79.0, 2.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Mak", 478, 20.1, 42.9, 24.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Makaron bezjajeczny", 363, 10.0, 1.6, 78.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Makaron czterojajeczny", 377, 12.0, 3.4, 76.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Makaron dwujajeczny", 373, 11.5, 2.6, 77.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Makaron na mleku", 66, 2.9, 2.3, 8.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Makowiec, ciasto", 348, 19.5, 40.8, 24.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Makrela świeża", 181, 18.7, 11.9, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Makrela wędzona", 221, 20.7, 15.5, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Makrela, filety z warzywami", 124, 12.0, 7.3, 3.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Makrela, sałatka pikantna", 181, 10.2, 13.2, 6.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Maliny", 29, 1.3, 0.3, 12.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Mandarynki", 42, 0.6, 0.2, 11.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Mango", 73, 0.5, 0.3, 17.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Marakuja", 34, 2.8, 0.2, 6.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Marchew", 27, 1.0, 0.2, 8.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Marchew mrożona", 24, 0.9, 0.2, 7.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Marchew z groszkiem", 64, 1.7, 3.1, 10.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Marchew zasmażana", 69, 1.0, 4.8, 8.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Margaryna Bona", 442, 0.0, 50.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Margaryna Flora", 531, 0.0, 60.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Margaryna Kama", 398, 0.0, 45.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Margaryna mleczna", 710, 0.3, 80.0, 0.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Margaryna Palma", 710, 0.3, 80.0, 0.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Margaryna Rama", 621, 0.1, 70.0, 0.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Margaryna Słoneczna", 710, 0.3, 80.0, 0.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Margaryna Tina", 442, 0.0, 45.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Margaryna zwykła", 710, 0.3, 80.0, 0.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Markizy, ciastka", 483, 5.6, 23.0, 64.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Mars, baton", 451, 3.6, 18.2, 68.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Masło ekstra", 735, 0.7, 82.5, 0.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Masło roślinne Nova", 442, 0.0, 50.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Masło roślinne zwykłe", 666, 0.3, 75.0, 0.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Masło śmietankowe", 659, 1.1, 73.5, 1.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Maślanka 0,5%", 37, 3.4, 0.5, 4.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Naleśniki z kapustą", 147, 3.2, 9.2, 15.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Naleśniki z serem", 242, 10.1, 10.3, 27.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Napoleonka, ciastko", 324, 5.0, 16.0, 39.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Napój Coca-cola", 42, 0.0, 0.0, 10.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Napój Kubuś Multiwitamina", 52, 0.0, 0.0, 12.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Napój Mirinda", 52, 0.0, 0.0, 12.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Napój mleczny jogurtowy", 82, 4.0, 1.9, 12.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Napój mleczny kakaowy", 81, 3.3, 2.1, 12.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Napój owocowy gazowany", 42, 0.0, 0.0, 10.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Napój Pepsi Cola", 42, 0.0, 0.0, 10.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Napój Red Bull", 45, 0.0, 0.0, 11.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Mączka ziemniaczana", 339, 0.6, 0.1, 83.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Mąka pszenna typ 500", 342, 9.2, 1.2, 74.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Mąka pszenna typ 550", 343, 9.6, 1.6, 74.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Medaliony z indyka", 247, 18.6, 17.9, 3.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Melon", 36, 0.9, 0.3, 8.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Mielonka", 171, 12.8, 11.7, 3.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Migdały", 572, 20.0, 52.0, 20.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Milky Way, baton", 448, 3.6, 16.2, 71.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Mintaj świeży", 73, 16.6, 0.6, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Miód pszczeli", 324, 0.0, 0.0, 79.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Mizeria ze śmietaną", 34, 1.0, 2.2, 2.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Mleko kozie", 68, 3.2, 4.1, 4.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Mleko owcze", 107, 6.0, 7.0, 5.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Mleko spożywcze 0,5%", 39, 3.5, 0.5, 5.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Mleko spożywcze 1,5%", 47, 3.4, 1.5, 5.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Mleko spożywcze 2,0%", 51, 3.4, 2.0, 4.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Mleko spożywcze 3,2%", 61, 3.3, 3.2, 4.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Mleko spożywcze 3,5%", 64, 3.3, 3.5, 4.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Mleko w proszku odtł.", 360, 35.7, 0.8, 51.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Mleko w proszku pełne", 479, 27.0, 24.0, 38.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Mleko zagęszczone niesłodzone", 131, 6.6, 7.5, 9.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Mleko zagęszczone słodzone", 326, 7.5, 8.0, 55.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Monte, deser czekoladowey", 195, 2.8, 13.3, 15.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Morela", 47, 0.9, 0.2, 11.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Morele suszone", 284, 5.4, 1.2, 72.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Morele, dżem niskosł.", 157, 0.4, 0.1, 38.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Morlinki, parówki", 448, 3.6, 16.2, 71.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Morszczuk świeży", 89, 17.2, 2.2, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Morwa", 48, 1.4, 0.4, 9.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Mus jabłkowy", 127, 2.2, 0.5, 28.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Musli z owocami suszonymi", 325, 8.4, 3.4, 72.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Musli z rodzynkami i orzechami", 375, 11.5, 12.7, 62.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Musztarda", 162, 5.7, 6.4, 22.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Napój Sprite", 42, 0.0, 0.0, 10.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Nektar owocowy", 63, 0.2, 0.4, 14.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Nektarynka", 53, 0.9, 0.2, 11.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Nesquik, kakao, proszek", 380, 3.5, 3.0, 84.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Nestle Corn Flakes, płatki kukurydziane", 370, 7.3, 0.8, 83.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Nestle Lion, baton", 491, 7.4, 22.7, 64.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Nóżki wieprzowe", 276, 23.0, 20.4, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Nutella, krem czekoladowy", 45, 0.0, 0.0, 11.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ocet winny", 20, 0.0, 0.0, 5.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ogórek", 13, 0.7, 0.1, 2.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ogórek kwaszony", 11, 1.0, 0.1, 1.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Olej kukurydziany", 884, 0.0, 100.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Olej rzepakowo-sojowy", 884, 0.0, 100.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Olej rzepakowy", 884, 0.0, 100.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Olej słonecznikowy", 884, 0.0, 100.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Olej sojowy", 884, 0.0, 100.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Oliwa z oliwek", 882, 0.0, 99.6, 0.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Oliwki", 147, 1.4, 13.9, 4.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Oliwki zielone marynowane", 125, 1.4, 12.7, 4.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Omlet biszkoptowy ze szpinakiem", 151, 6.4, 10.4, 10.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Orzechy arachidowe", 560, 25.7, 46.1, 19.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Orzechy laskowe", 640, 14.4, 63.0, 14.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Orzechy pistacjowe", 589, 20.5, 48.5, 25.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Orzechy włoskie", 645, 16.0, 60.3, 18.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ostrygi", 85, 5.0, 5.0, 5.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Otręby pszenne", 185, 16.0, 4.6, 61.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ozór cielęcy", 106, 17.1, 4.2, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ozór wieprzowy", 165, 16.5, 11.1, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Paluszki solone", 385, 9.9, 4.9, 75.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Papaja", 43, 0.6, 0.1, 9.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Papryka czerwona", 28, 1.3, 0.5, 6.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Papryka czerw. kons.", 30, 0.8, 1.5, 5.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Papryka nadz. mięsem", 160, 4.4, 10.6, 13.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Papryka zielona", 18, 1.1, 0.3, 4.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Paprykarz Szczeciński", 178, 9.9, 11.9, 8.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Parówki", 342, 9.5, 34.3, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Parówki drobiowe", 259, 10.8, 22.4, 4.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Parówki Morlinki", 223, 12.4, 19.1, 0.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pasternak", 80, 1.2, 0.3, 18.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Paszteciki drożdż. mięsn.", 308, 8.4, 18.4, 28.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pasztet pieczony", 390, 17.0, 31.2, 13.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pasztet podlaski drob,", 228, 6.7, 21.1, 3.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pasztet z mięsa miesz.", 361, 15.0, 31.1, 6.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pączki", 376, 6.0, 16.0, 52.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pepsi, napój", 42, 0.0, 0.0, 10.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pestki dyni", 596, 29.0, 46.7, 15.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pędy bambusa", 34, 2.6, 0.3, 5.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pędy bambusa, kons.", 23, 1.7, 0.4, 3.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pieczarka, suszona", 331, 19.1, 2.1, 49.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pieczarka, świeża", 17, 2.7, 0.4, 2.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pieczeń cielęca, duszona", 193, 20.1, 11.8, 1.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pieczeń rzymska", 208, 14.4, 11.4, 12.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pieczeń wołowa duszona", 155, 15.8, 9.5, 2.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pieczywo chrupkie Wasa", 360, 12.0, 2.2, 73.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pieczywo tostowe", 305, 8.1, 4.7, 58.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pieczywo tost. graham", 273, 7.5, 4.2, 53.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Piernik z bakaliami", 341, 5.9, 9.8, 59.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pierniki alpejskie", 367, 4.0, 9.7, 66.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pierniki beskidzkie", 338, 3.5, 1.6, 77.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pierogi leniwe", 242, 14.5, 13.9, 15.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pierogi ruskie", 166, 5.6, 5.0, 25.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pierogi z mięsem", 219, 12.0, 11.6, 17.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pierogi z serem", 238, 10.9, 9.9, 26.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pierogi z truskawkami", 240, 3.8, 11.4, 32.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pietruszka, korzeń", 38, 2.6, 0.5, 10.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pietruszka, nać", 41, 4.4, 0.4, 9.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pikling", 215, 21.8, 14.3, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Piwo bezalkoholowe", 27, 0.2, 0.0, 5.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Piwo ciemne pełne", 42, 0.4, 0.0, 4.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Piwo jasne mocne", 64, 7.0, 0.0, 5.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Piwo jasne pełne", 49, 0.5, 0.0, 3.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pizza mięsno-ziołowa", 327, 16.1, 13.4, 36.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pizza z pieczarkami i cebulą", 289, 12.0, 13.3, 32.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Placki ziemniaczane", 231, 3.6, 14.5, 23.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Płastuga, świeża", 86, 17.1, 1.9, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Płatki jęczmienne", 355, 9.8, 3.6, 79.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Płatki kukurydziane", 363, 6.9, 2.5, 83.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Płatki owsiane", 366, 11.9, 7.2, 69.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Płatki owsiane na mleku", 63, 2.7, 2.3, 8.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Płatki pszenne", 351, 9.0, 3.0, 81.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Płatki żytnie", 343, 6.4, 3.2, 82.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Polędwica sopocka", 165, 19.9, 9.1, 0.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Polędwica wołowa piecz.", 168, 19.7, 9.9, 2.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Polędwica z indyka", 105, 15.8, 4.6, 0.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Polędwica z kurczaka", 93, 20.4, 1.2, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pomarańcza", 44, 0.9, 0.2, 11.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pomarańcze, dżem niskosłodzony", 159, 0.3, 0.1, 39.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pomidor", 15, 0.9, 0.2, 3.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Popcorn bez tłuszczu", 397, 12.0, 4.2, 77.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Popcorn z tłuszczem", 518, 9.0, 28.1, 57.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Por", 24, 2.2, 0.3, 5.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Porzeczki białe", 33, 1.0, 0.2, 13.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Porzeczki czarne", 35, 1.3, 0.2, 14.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Porzeczki czerwone", 31, 1.1, 0.2, 13.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Potrawka z kurczaka", 148, 13.2, 9.0, 4.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Poziomki", 33, 0.8, 0.5, 8.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Precelki", 385, 9.1, 3.5, 79.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Przyprawa Maggi", 17, 2.7, 0.0, 58.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pstrąg strumieniowy", 97, 19.2, 2.1, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pstrąg tęczowy", 160, 18.9, 9.6, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ptysie z bitą śmietaną", 346, 5.4, 25.0, 25.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pulpety mielone", 223, 18.7, 11.1, 13.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pumpernikiel", 252, 5.8, 2.0, 58.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pyzy", 210, 3.7, 6.2, 37.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Pyzy z mięsem", 292, 7.8, 14.0, 36.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Rabarbar", 9, 0.5, 0.1, 4.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Risotto z mięsem", 229, 7.4, 11.8, 24.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Risotto z mięsem i warzywami", 185, 6.6, 10.0, 18.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Rodzynki suszone", 277, 2.3, 0.5, 71.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Rolada biszkoptowa", 304, 6.9, 5.4, 56.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Rolada wieprzowa", 412, 21.1, 32.5, 10.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ryż biały", 344, 5.7, 0.7, 78.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ryż brązowy", 322, 7.1, 1.9, 76.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ryż na mleku", 66, 2.7, 2.1, 9.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ryż na sypko", 135, 2.4, 1.5, 28.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ryż preparowany", 361, 6.3, 1.6, 84.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ryż z jabłkami", 152, 2.0, 2.1, 32.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Rzepa", 26, 1.1, 0.3, 8.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Rzodkiewka", 14, 1.0, 0.2, 4.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Salami popularne", 568, 21.6, 53.7, 1.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Salceson czarny", 336, 12.6, 32.0, 0.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Salceson włoski", 318, 14.6, 29.3, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Sałata", 14, 1.4, 0.2, 2.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Sałata zielona z olejem", 55, 0.9, 4.7, 3.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Sałata zielona ze śmietaną", 40, 1.4, 2.3, 4.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Sałatka jarzynowa z maj.", 192, 2.9, 16.5, 10.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Sałatka z czerw. kapusty", 83, 1.4, 6.5, 7.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Sandacz świeży", 84, 19.2, 0.7, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Sardyna świeża", 169, 20.6, 9.6, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Sardyna w oleju", 221, 24.1, 13.9, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Sardyna w pomidorach", 162, 17.0, 9.9, 1.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Sarnina", 102, 20.8, 1.9, 0.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Schab pieczony", 291, 30.4, 18.7, 0.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Schab surowy wieprzowy", 174, 21.0, 10.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Schab wędzony", 136, 25.0, 4.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Seler, korzeń", 21, 1.6, 0.3, 7.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Seler, nać", 13, 1.0, 0.2, 3.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ser Brie pełnotłusty", 329, 19.8, 28.0, 0.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ser Camembert pełnotłusty", 291, 21.4, 23.0, 0.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ser Cheddar pełnotłusty", 391, 27.1, 23.4, 0.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ser Edamski tłusty", 313, 36.1, 23.4, 0.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ser Ementaler pełnotłusty", 380, 28.8, 29.7, 0.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ser Feta", 215, 17.0, 16.0, 1.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ser Gouda tłusty", 316, 27.9, 22.9, 0.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ser Myśliwski pełnotłusty", 346, 25.5, 27.4, 0.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ser Parmezan", 452, 41.5, 32.0, 0.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ser Rokpol pełnotłusty", 363, 15.8, 9.5, 2.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ser Salami pełnotłusty", 351, 25.2, 28.1, 0.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ser topiony edamski", 298, 13.5, 27.0, 1.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ser twarogowy chudy", 99, 19.8, 0.5, 3.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ser twarogowy półtłusty", 133, 18.7, 4.7, 3.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ser twarogowy tłusty", 175, 17.7, 10.1, 3.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ser Tylżycki pełnostłusty", 353, 26.1, 27.9, 0.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ser Tylżycki tłusty", 334, 27.8, 25.0, 0.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Serca wieprzowe", 165, 16.9, 4.8, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Serek Fromage naturalny", 379, 10.2, 37.1, 2.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Serek Fromage z czosnkiem", 367, 10.0, 35.2, 4.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Serek homogenizowany", 161, 12.7, 11.0, 3.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Serek homog. truskawkowy", 168, 15.3, 3.9, 17.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Serek homog. waniliowy", 159, 16.8, 4.2, 13.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Serek twarogowy ziarnisty", 101, 12.3, 4.3, 3.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Sernik krakowski", 325, 13.8, 13.4, 37.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Sernik wiedeński", 305, 12.5, 15.5, 31.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Sernik z rodzynkami", 333, 13.9, 13.4, 39.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Serwatka płynna", 25, 0.8, 0.1, 5.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Sezamki", 402, 10.2, 26.4, 34.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Skrobia ziemniaczana", 343, 0.6, 0.1, 83.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Słonecznik, nasiona", 561, 24.4, 43.7, 24.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Słonina", 797, 2.4, 89.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Smalec", 880, 0.0, 99.5, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Soczewica, suche nasiona", 327, 25.4, 3.0, 57.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Soczewica, kiełki", 119, 9.0, 0.6, 22.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Soja, kiełki", 141, 13.1, 6.7, 9.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Soja, suche nasiona", 382, 34.2, 19.6, 32.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Sola świeża", 83, 17.5, 1.4, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Sok ananasowy", 48, 0.3, 0.1, 11.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Sok cytrynowy", 30, 0.4, 0.3, 6.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Sok grejpfrutowy", 40, 0.5, 0.1, 9.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Sok jabłkowy", 42, 0.1, 0.1, 10.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Sok marchw. brzoskw.", 44, 0.5, 0.1, 11.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Sok marchw. jabłk.", 46, 0.5, 0.3, 12.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Sok marchwiowy", 43, 0.4, 0.1, 11.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Sok pomarańczowy", 43, 0.6, 0.1, 9.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Sok pomidorowy", 13, 0.8, 0.1, 2.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Sok wielowarzywny", 25, 1.0, 0.3, 5.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Sok z czarnej porzeczki", 53, 0.3, 0.1, 12.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Sprite, napój", 42, 0.0, 0.0, 10.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Stek wieprzowy", 472, 21.7, 42.7, 1.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Surówka wielowarzywna z jogurtem", 36, 1.7, 0.6, 7.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Surówka z cykorii i jabłek", 162, 1.0, 16.4, 3.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Surówka z kap. białej", 67, 1.6, 4.7, 7.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Surówka z kap. kwaszonej", 68, 0.9, 4.7, 7.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Surówka z kap. pekińskiej", 94, 1.6, 8.1, 6.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Surówka z marchwi i jabłek", 59, 1.0, 0.3, 16.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Surówka z ogórków i pomidorów", 32, 1.1, 1.8, 3.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Surówka z owoców", 102, 0.5, 0.3, 25.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Surówka z owoców i warzyw", 147, 1.1, 14.3, 5.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Surówka z papryki", 90, 1.0, 7.5, 6.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Surówka z pomidorów", 14, 0.8, 0.2, 14.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Surówka z porów z jabłkami", 140, 1.7, 12.5, 7.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Surówka z rzodkiewki", 93, 7.5, 3.5, 9.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Surówka z selerów", 92, 1.1, 7.5, 8.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Surówka z selerów, jabłka i marchwi", 60, 0.9, 0.4, 16.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Syrop truskawkowy", 262, 0.2, 0.1, 62.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Szampan półsłodki, alkohol", 97, 0.2, 0.0, 7.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Szampan wytrawny", 83, 0.1, 0.0, 3.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Szampan słodki", 117, 0.2, 0.0, 12.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Szczaw", 21, 1.1, 0.8, 4.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Szczupak świeży", 82, 18.4, 0.8, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Szczypiorek", 29, 4.1, 0.8, 3.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Szparagi", 18, 1.9, 0.2, 3.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Szpinak", 16, 2.6, 0.4, 3.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Szpinak mrożony", 15, 2.3, 0.4, 2.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Szpinak zasmażany", 83, 3.7, 6.1, 6.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Sztuka mięsa wołowego", 224, 30.6, 10.3, 3.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Szynka delikatesowa z kurczaka", 123, 18.2, 5.6, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Szynka wiejska", 253, 17.1, 20.3, 0.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Szynka wieprzowa gotowana", 233, 16.4, 18.3, 1.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Szynka wołowa gotowana", 107, 20.9, 2.0, 1.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Szynka z indyka", 84, 17.1, 1.6, 0.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Szynka z udka kurczaka", 117, 17.2, 5.3, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Szynkówka wieprzowa", 191, 13.6, 14.7, 1.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Śliwki", 45, 0.6, 0.2, 11.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Śliwki suszone", 267, 3.5, 1.2, 68.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Śliwki dżem niskosłodzony", 153, 0.3, 0.1, 37.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Śliwki dżem wysokosłodzony", 251, 0.3, 0.1, 62.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Śliwki, powidła", 214, 1.0, 0.2, 53.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Śledź solony", 218, 19.8, 15.4, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Śledź świeży", 162, 16.3, 10.7, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Śledź w oleju, konserwa", 343, 19.7, 29.4, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Śledź w pomidorach, konserwa", 177, 13.7, 12.8, 1.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Śmietana 12%", 133, 2.7, 12.0, 3.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Śmietana 18%", 184, 2.5, 18.0, 3.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Śmietanka do kawy 9%", 107, 2.8, 9.0, 4.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Śmietanka kremowa 30%", 287, 2.2, 30.0, 3.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Teatralny, wafel", 546, 8.0, 31.0, 58.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Tic-tac, drażetki", 390, 0.0, 0.0, 97.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Tłuszcz roślinny Planta", 900, 0.0, 100.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Toffifee, czekoladki", 535, 6.0, 31.0, 58.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Tran", 900, 0.0, 100.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Truskawki", 28, 0.7, 0.4, 7.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Truskawki w galaretce", 126, 15.4, 0.2, 16.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Truskawki z bitą śmietaną", 127, 1.1, 10.4, 8.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Truskawki, dżem niskosłodzony", 153, 0.3, 0.2, 37.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Truskawki, dżem wysokosłodzony", 252, 0.3, 0.2, 62.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Tuńczyk w oleju", 190, 27.1, 9.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Tuńczyk w wodzie", 96, 21.0, 1.2, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Twix, baton", 487, 5.3, 23.2, 64.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Udko z kurczaka bez skóry", 125, 17.8, 6.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Udko z kurczaka ze skórą", 161, 17.8, 10.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Udziec barani", 234, 18.0, 18.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Udziec cielęcy", 108, 19.9, 3.1, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wafle Familijne", 533, 7.1, 29.6, 59.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wafle Grześki", 550, 8.5, 34.5, 51.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wafle Kinder Bueno", 532, 5.5, 35.5, 47.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wafle nadziewane", 519, 8.3, 27.5, 60.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wafle Prince Polo", 534, 4.8, 31.5, 57.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wafle Princessa", 562, 4.1, 34.6, 58.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wafle Teatralne", 546, 8.0, 31.0, 58.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wafle w czekoladzie", 553, 7.4, 33.9, 55.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wasa, pieczywo chrupkie", 360, 12.0, 2.2, 73.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wątroba cielęca", 124, 19.2, 3.3, 4.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wątroba drobiowa", 136, 19.1, 6.3, 0.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wątroba wieprzowa", 130, 22.0, 3.4, 2.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wątroba wołowa", 125, 20.0, 3.1, 4.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wątróbka wieprzowa saute", 239, 20.5, 15.5, 4.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wermut, wino", 104, 0.0, 0.0, 7.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wędzonka wołowa gotowana", 102, 17.8, 3.1, 0.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Węgorz świeży", 281, 12.7, 25.6, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Węgorz wędzony", 326, 17.9, 28.6, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Whisky, alkohol", 225, 0.0, 0.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wieprzowina duszona", 225, 11.4, 19.8, 1.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wieprzowina gotowana", 364, 22.6, 30.0, 3.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wieprzowina, boczek", 510, 10.1, 53.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wieprzowina, golonka", 294, 18.6, 24.7, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wieprzowina, karkówka", 267, 16.1, 22.8, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wieprzowina, łopatka", 257, 16.0, 21.7, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wieprzowina, podgardle", 630, 7.4, 67.8, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wieprzowina, schab surowy", 174, 21.0, 10.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wieprzowina, szynka surowa", 261, 18.0, 21.3, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wieprzowina, żeberka", 321, 15.2, 29.3, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wino białe półsłodkie", 92, 0.0, 0.0, 4.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wino białe półwytrawne", 78, 0.0, 0.0, 3.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wino białe wytrawne", 73, 0.0, 0.0, 2.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wino czerwone półsłodkie", 96, 0.0, 0.0, 5.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wino czerwone słodkie", 106, 0.1, 0.0, 8.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wino czerwone wytrawne", 75, 0.0, 0.0, 3.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Winogrona", 69, 0.5, 0.2, 17.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wiórki kokosowe", 606, 5.6, 63.2, 27.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wiśnie", 47, 0.9, 0.4, 10.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wiśnie, dżem niskosł.", 154, 0.4, 0.2, 37.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wiśnie, dżem wysokosł.", 252, 0.4, 0.2, 61.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Włoszczyzna mrożona", 25, 1.4, 0.3, 7.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wołowina, polędwica", 112, 20.1, 3.5, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wołowina, pieczeń", 117, 20.9, 3.6, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wołowina, rostbef", 152, 21.5, 7.3, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wołowina, rozbratel", 157, 16.7, 10.1, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wołowina, szponder", 217, 19.3, 15.7, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Wódka, średnio", 225, 0.0, 0.0, 0.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Zarodki pszenne", 377, 27.5, 9.4, 45.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ziemniaki późne", 85, 1.9, 0.1, 20.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ziemniaki puree", 90, 2.1, 1.4, 18.4);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ziemniaki wczesne", 69, 1.8, 0.1, 16.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Ziemniaki z tłuszczem", 106, 2.0, 3.1, 18.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Zupa cebulowa", 44, 1.4, 2.7, 4.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Zupa cytrynowa z ryżem", 58, 1.4, 2.2, 8.7);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Zupa fasolowa", 62, 4.0, 1.8, 10.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Zupa grochowa", 66, 4.4, 2.4, 8.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Zupa grzybowa zabielana", 26, 1.3, 1.8, 1.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Zupa jarzynowa", 43, 1.7, 1.8, 6.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Zupa jesienna mrożona", 27, 1.6, 0.2, 7.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Zupa kalafiorowa", 28, 1.6, 0.5, 4.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Zupa kalafiorowa mrożona", 22, 2.0, 0.2, 5.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Zupa neapolitańska", 63, 2.2, 2.6, 8.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Zupa ogórkowa", 42, 1.4, 2.0, 5.0);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Zupa owocowa z jabłek", 42, 0.1, 0.1, 11.8);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Zupa pomidorowa", 11, 1.0, 0.1, 2.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Zupa pomidorowa z makaronem", 35, 1.5, 1.8, 3.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Zupa pomidorowa z ryżem", 37, 1.5, 1.8, 3.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Zupa pomidorowa zabielana", 28, 1.3, 1.8, 1.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Zupa selerowa", 37, 1.6, 1.8, 4.5);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Zupa selerowa z grzankami", 51, 1.8, 1.9, 8.1);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Zupa szczawiowa", 40, 1.6, 2.5, 2.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Zupa szpinakowa z ziemniakami", 40, 2.2, 0.9, 6.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Zupa z fasoli szparagowej", 43, 2.2, 0.6, 8.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Zupa z porów z makaronem", 58, 2.4, 1.4, 10.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Zupa z zielonego groszku", 56, 3.2, 1.2, 11.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Zupa ziemniaczana", 39, 1.4, 1.1, 6.6);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Żeberka wieprzowe duszone", 210, 7.9, 19.2, 2.2);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Żółtko jaja kurzego", 314, 15.5, 28.2, 0.3);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Żurawiny", 51, 0.4, 0.1, 19.9);
INSERT INTO product(name,calories,proteins,fats,carbonhydrates) VALUES ("Żurek", 124, 2.2, 3.1, 23.5);







INSERT INTO user_table(name) VALUES('root');
INSERT INTO meal(name, user_id, date) VALUES('Obiad', 1, '2018-06-06');
INSERT INTO products_in_meal(fk_meal, fk_product, quantity) VALUES(1, 339, 150);
INSERT INTO products_in_meal(fk_meal, fk_product, quantity) VALUES(1, 555, 100);
INSERT INTO products_in_meal(fk_meal, fk_product, quantity) VALUES(1, 636, 50);


